// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm9vuPD4rPrtVaVBaYEZY7A675CSiPy4I',
    appId: '1:137322851401:web:44789ef42538540baa6398',
    messagingSenderId: '137322851401',
    projectId: 'rockifyxx01',
    authDomain: 'rockifyxx01.firebaseapp.com',
    storageBucket: 'rockifyxx01.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUn8IM7seBnidjMg0Fpg5YkdJqO3V-_-Q',
    appId: '1:137322851401:android:fc30ebfdf51e04f0aa6398',
    messagingSenderId: '137322851401',
    projectId: 'rockifyxx01',
    storageBucket: 'rockifyxx01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGHwzPw4IM4wzpziN1lhzDhPpUOhKyVl4',
    appId: '1:137322851401:ios:38d88df9cf896715aa6398',
    messagingSenderId: '137322851401',
    projectId: 'rockifyxx01',
    storageBucket: 'rockifyxx01.appspot.com',
    iosBundleId: 'com.example.rockify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGHwzPw4IM4wzpziN1lhzDhPpUOhKyVl4',
    appId: '1:137322851401:ios:38d88df9cf896715aa6398',
    messagingSenderId: '137322851401',
    projectId: 'rockifyxx01',
    storageBucket: 'rockifyxx01.appspot.com',
    iosBundleId: 'com.example.rockify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBm9vuPD4rPrtVaVBaYEZY7A675CSiPy4I',
    appId: '1:137322851401:web:f46765c43fbc57a0aa6398',
    messagingSenderId: '137322851401',
    projectId: 'rockifyxx01',
    authDomain: 'rockifyxx01.firebaseapp.com',
    storageBucket: 'rockifyxx01.appspot.com',
  );

}